CREATE TABLE usuarios (
	id		BIGINT 		NOT NULL AUTO_INCREMENT,
	login		VARCHAR(50) 	NOT NULL UNIQUE,
	nombre		VARCHAR(50) 	NOT NULL UNIQUE,
	email		VARCHAR(50) 	NOT NULL UNIQUE,
	contrasena	VARCHAR(300)	NOT NULL,

	PRIMARY KEY(id)
);